// <auto-generated />
using CIS_174_Project.Models.Olympics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS_174_Project.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20250303194700_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameTypeOlympicGameTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameTypeOlympicGameTypeID");

                    b.HasIndex("SportTypeID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "canada",
                            CountryFlag = "~/images/olympics/canada.png",
                            Name = "Canada",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "sweden",
                            CountryFlag = "~/images/olympics/sweden.png",
                            Name = "Sweden",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "greatbritain",
                            CountryFlag = "~/images/olympics/greatbritain.png",
                            Name = "Great Britain",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "jamaica",
                            CountryFlag = "~/images/olympics/jamaica.png",
                            Name = "Jamaica",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "italy",
                            CountryFlag = "~/images/olympics/italy.png",
                            Name = "Italy",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "japan",
                            CountryFlag = "~/images/olympics/japan.png",
                            Name = "Japan",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "germany",
                            CountryFlag = "~/images/olympics/germany.png",
                            Name = "Germany",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "china",
                            CountryFlag = "~/images/olympics/china.png",
                            Name = "China",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "mexico",
                            CountryFlag = "~/images/olympics/mexico.png",
                            Name = "Mexico",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "brazil",
                            CountryFlag = "~/images/olympics/brazil.png",
                            Name = "Brazil",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "netherlands",
                            CountryFlag = "~/images/olympics/netherlands.png",
                            Name = "Netherlands",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "usa",
                            CountryFlag = "~/images/olympics/usa.png",
                            Name = "USA",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "thailand",
                            CountryFlag = "~/images/olympics/thailand.png",
                            Name = "Thailand",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "uruguay",
                            CountryFlag = "~/images/olympics/uruguay.png",
                            Name = "Uruguay",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "ukraine",
                            CountryFlag = "~/images/olympics/ukraine.png",
                            Name = "Ukraine",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "austria",
                            CountryFlag = "~/images/olympics/austria.png",
                            Name = "Austria",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "pakistan",
                            CountryFlag = "~/images/olympics/pakistan.png",
                            Name = "Pakistan",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "zimbabwe",
                            CountryFlag = "~/images/olympics/zimbabwe.png",
                            Name = "Zimbabwe",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "france",
                            CountryFlag = "~/images/olympics/france.png",
                            Name = "France",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "cyprus",
                            CountryFlag = "~/images/olympics/cyprus.png",
                            Name = "Cyprus",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "russia",
                            CountryFlag = "~/images/olympics/russia.png",
                            Name = "Russia",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "finland",
                            CountryFlag = "~/images/olympics/finland.png",
                            Name = "Finland",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "slovakia",
                            CountryFlag = "~/images/olympics/slovakia.png",
                            Name = "Slovakia",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "portugal",
                            CountryFlag = "~/images/olympics/portugal.png",
                            Name = "Portugal",
                            SportTypeID = "outdoor"
                        });
                });

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.OlympicGameType", b =>
                {
                    b.Property<string>("OlympicGameTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OlympicGameTypeID");

                    b.ToTable("OlympicGames");

                    b.HasData(
                        new
                        {
                            OlympicGameTypeID = "summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            OlympicGameTypeID = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            OlympicGameTypeID = "paralympic",
                            Name = "Paralympic Games"
                        },
                        new
                        {
                            OlympicGameTypeID = "youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.SportType", b =>
                {
                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportTypeID");

                    b.ToTable("SportTypes");

                    b.HasData(
                        new
                        {
                            SportTypeID = "indoor",
                            Name = "Indoor"
                        },
                        new
                        {
                            SportTypeID = "outdoor",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.Country", b =>
                {
                    b.HasOne("CIS_174_Project.Models.Olympics.OlympicGameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeOlympicGameTypeID");

                    b.HasOne("CIS_174_Project.Models.Olympics.SportType", "SportType")
                        .WithMany()
                        .HasForeignKey("SportTypeID");

                    b.Navigation("GameType");

                    b.Navigation("SportType");
                });
#pragma warning restore 612, 618
        }
    }
}
