// <auto-generated />
using CIS_174_Project.Models.Olympics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIS_174_Project.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20250303203752_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameTypeOlympicGameTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CountryID");

                    b.HasIndex("GameTypeOlympicGameTypeID");

                    b.HasIndex("SportTypeID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "ca",
                            CountryFlag = "~/images/olympics/ca.png",
                            Name = "Canada",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "se",
                            CountryFlag = "~/images/olympics/se.png",
                            Name = "Sweden",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "gb",
                            CountryFlag = "~/images/olympics/gb.png",
                            Name = "Great Britain",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "jm",
                            CountryFlag = "~/images/olympics/jm.png",
                            Name = "Jamaica",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "it",
                            CountryFlag = "~/images/olympics/it.png",
                            Name = "Italy",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "jp",
                            CountryFlag = "~/images/olympics/jp.png",
                            Name = "Japan",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "de",
                            CountryFlag = "~/images/olympics/de.png",
                            Name = "Germany",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "cn",
                            CountryFlag = "~/images/olympics/cn.png",
                            Name = "China",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "mx",
                            CountryFlag = "~/images/olympics/mx.png",
                            Name = "Mexico",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "br",
                            CountryFlag = "~/images/olympics/br.png",
                            Name = "Brazil",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "nl",
                            CountryFlag = "~/images/olympics/nl.png",
                            Name = "Netherlands",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "us",
                            CountryFlag = "~/images/olympics/us.png",
                            Name = "USA",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "th",
                            CountryFlag = "~/images/olympics/th.png",
                            Name = "Thailand",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "uy",
                            CountryFlag = "~/images/olympics/uy.png",
                            Name = "Uruguay",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "ua",
                            CountryFlag = "~/images/olympics/ua.png",
                            Name = "Ukraine",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "at",
                            CountryFlag = "~/images/olympics/at.png",
                            Name = "Austria",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "pk",
                            CountryFlag = "~/images/olympics/pk.png",
                            Name = "Pakistan",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "zw",
                            CountryFlag = "~/images/olympics/zw.png",
                            Name = "Zimbabwe",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "fr",
                            CountryFlag = "~/images/olympics/fr.png",
                            Name = "France",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "cy",
                            CountryFlag = "~/images/olympics/cy.png",
                            Name = "Cyprus",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "ru",
                            CountryFlag = "~/images/olympics/ru.png",
                            Name = "Russia",
                            SportTypeID = "indoor"
                        },
                        new
                        {
                            CountryID = "fi",
                            CountryFlag = "~/images/olympics/fi.png",
                            Name = "Finland",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "sk",
                            CountryFlag = "~/images/olympics/sk.png",
                            Name = "Slovakia",
                            SportTypeID = "outdoor"
                        },
                        new
                        {
                            CountryID = "pt",
                            CountryFlag = "~/images/olympics/pt.png",
                            Name = "Portugal",
                            SportTypeID = "outdoor"
                        });
                });

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.OlympicGameType", b =>
                {
                    b.Property<string>("OlympicGameTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OlympicGameTypeID");

                    b.ToTable("OlympicGames");

                    b.HasData(
                        new
                        {
                            OlympicGameTypeID = "summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            OlympicGameTypeID = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            OlympicGameTypeID = "paralympic",
                            Name = "Paralympic Games"
                        },
                        new
                        {
                            OlympicGameTypeID = "youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.SportType", b =>
                {
                    b.Property<string>("SportTypeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SportTypeID");

                    b.ToTable("SportTypes");

                    b.HasData(
                        new
                        {
                            SportTypeID = "indoor",
                            Name = "Indoor"
                        },
                        new
                        {
                            SportTypeID = "outdoor",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("CIS_174_Project.Models.Olympics.Country", b =>
                {
                    b.HasOne("CIS_174_Project.Models.Olympics.OlympicGameType", "GameType")
                        .WithMany()
                        .HasForeignKey("GameTypeOlympicGameTypeID");

                    b.HasOne("CIS_174_Project.Models.Olympics.SportType", "SportType")
                        .WithMany()
                        .HasForeignKey("SportTypeID");

                    b.Navigation("GameType");

                    b.Navigation("SportType");
                });
#pragma warning restore 612, 618
        }
    }
}
